export const iconMap: {[key: string]: any} = {
  comestibles: require("../../assets/images/linkType/comestibles.png"),
  facebook: require("../../assets/images/linkType/facebook.png"),
  instagram: require("../../assets/images/linkType/instagram.png"),
  line: require("../../assets/images/linkType/line.png"),
  linkedin: require("../../assets/images/linkType/linkedin.png"),
  meet: require("../../assets/images/linkType/meet.png"),
  messenger: require("../../assets/images/linkType/messenger.png"),
  online: require("../../assets/images/linkType/online.png"),
  paginaweb: require("../../assets/images/linkType/paginaweb.png"),
  panaderia: require("../../assets/images/linkType/panaderia.png"),
  pinterest: require("../../assets/images/linkType/pinterest.png"),
  snapchat: require("../../assets/images/linkType/snapchat.png"),
  telefono: require("../../assets/images/linkType/telefono.png"),
  telegram: require("../../assets/images/linkType/telegram.png"),
  threads: require("../../assets/images/linkType/threads.png"),
  tienda: require("../../assets/images/linkType/tienda.png"),
  tiktok: require("../../assets/images/linkType/tiktok.png"),
  wechat: require("../../assets/images/linkType/wechat.png"),
  whatssapp: require("../../assets/images/linkType/whatsapp.png"),
  whatssappb: require("../../assets/images/linkType/whatssappb.png"),
  x: require("../../assets/images/linkType/x.png"),
  youtube: require("../../assets/images/linkType/youtube.png"),
  zoom: require("../../assets/images/linkType/zoom.png"),
};
